# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=100)),
                ('action_ower', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
    ]
